services:
  mediator.api:
    image: mediator.api
    build:
      context: ../
      dockerfile: Mediator.API/Dockerfile
    user: root
    ports:
      - 5000:8080
    env_file: .env
  postgres:
      image: postgres:latest
      env_file: .env
      ports:
        - 5430:5432

